server:
  port: 11120

spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
    # sentinel控制台地址
    sentinel:
      transport:
        dashboard: localhost:8849
        port: 8719
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
  task:
    execution:
      pool:
        core-size: 5 # 配置异步任务功能线程池
        max-size: 50
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-returns: true # 消息正确抵达队列进行回调
    template:
      mandatory: true  # 强制要求消息必须被路由到一个队列。如果消息无法路由，会触发一个回调，通常用于处理无法投递的消息
    listener:
      simple:
        acknowledge-mode: manual # 手动签收

# 暴露所有监控端点，使得sentinel可以实时监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true