spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
  application:
    name: gulimall-auth
  thymeleaf:
    cache: false

server:
  port: 11117

# 开启com.zljin.gulimall目录下的debug level日志
logging:
  level:
    com.zljin.gulimall: debug