spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
    # sentinel控制台地址
    sentinel:
      transport:
        dashboard: localhost:8849
        port: 8719
  application:
    name: gulimall-auth
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis

server:
  port: 11117
  servlet:
    session:
      timeout: 30m

oauth:
  github:
    clientId: Ov23li874WQS0ndohc8Y
    clientSecret: NWRkMDgwMDJhMmI3YzVlNTZjZjUxODEyN2YzMjFlMjRmZGFiYWQ2OQ==
    redirectUrl: http://auth.gulimall.com/oauth2.0/github/success
    oauth2SuccessUrl: https://github.com/login/oauth/access_token?client_id=CLIENT_ID&client_secret=CLIENT_SECRET&code=CODE&redirect_uri=CALLBACK
    oauthOpenApiUrl1: https://api.github.com/user


# 暴露所有监控端点，使得sentinel可以实时监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true