spring:
  application:
    name: gulimall-multihub
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false

server:
  port: 11118

logging:
  level:
    com.zljin.gulimall: debug